# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:29
from __future__ import unicode_literals

import code_doc.models.artifacts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("code_doc", "0022_auto_20150903_2206")]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="artifactfile",
            field=models.FileField(
                help_text=b"the artifact file that will be stored on the server",
                max_length=1024,
                upload_to=code_doc.models.artifacts.get_artifact_location,
            ),
        ),
        migrations.AlterField(
            model_name="copyrightholder",
            name="year",
            field=models.IntegerField(default=2016),
        ),
    ]
