# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_doc', '0024_auto_20170220_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrepository',
            options={'verbose_name_plural': 'Project repositories'},
        ),
        migrations.AlterModelOptions(
            name='projectseries',
            options={'permissions': (('series_view', 'User/group has access to this serie and its content'), ('series_edit', 'User/group can edit the definition of this series'), ('series_artifact_add', 'User/group is allowed to add an artifact'), ('series_artifact_delete', 'User/group is allowed to delete an artifact')), 'verbose_name_plural': 'Project series'},
        ),
        migrations.AlterUniqueTogether(
            name='projectrepository',
            unique_together=set([('project', 'code_source_url')]),
        ),
    ]
