# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:23
from __future__ import unicode_literals

import code_doc.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("code_doc", "0025_auto_20170220_2320")]

    operations = [
        migrations.AlterField(
            model_name="copyrightholder",
            name="year",
            field=models.IntegerField(default=code_doc.models.models._current_year),
        )
    ]
